"""initial_schema

Revision ID: dcf929a58faa
Revises: 
Create Date: 2026-09-03 23:37:28.672368

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf929a58faa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpt_codes',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('short_description', sa.String(length=255), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('medicare_national_rate', sa.Float(), nullable=False),
    sa.Column('unbundling_group', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_cpt_codes_code'), 'cpt_codes', ['code'], unique=False)
    op.create_index(op.f('ix_cpt_codes_unbundling_group'), 'cpt_codes', ['unbundling_group'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cognito_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cognito_sub'), 'users', ['cognito_sub'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('s3_key', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCANNING', 'CLEARED', 'DISPUTED', 'ERROR', name='documentstatus', native_enum=False), nullable=False),
    sa.Column('textract_job_id', sa.String(length=255), nullable=True),
    sa.Column('raw_textract_json', sa.JSON(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('policy_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=False),
    sa.Column('is_covered', sa.Boolean(), nullable=False),
    sa.Column('requires_preauth', sa.Boolean(), nullable=False),
    sa.Column('coinsurance_rate', sa.Float(), nullable=False),
    sa.Column('policy_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cpt_code'], ['cpt_codes.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_rules_cpt_code'), 'policy_rules', ['cpt_code'], unique=False)
    op.create_index(op.f('ix_policy_rules_plan_id'), 'policy_rules', ['plan_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('patient_info', sa.JSON(), nullable=False),
    sa.Column('provider_info', sa.JSON(), nullable=False),
    sa.Column('disputed_codes', sa.JSON(), nullable=False),
    sa.Column('agent_reasoning', sa.Text(), nullable=False),
    sa.Column('dispute_letter_markdown', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'DISMISSED', name='disputestatus', native_enum=False), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_document_id'), 'disputes', ['document_id'], unique=True)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_document_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_policy_rules_plan_id'), table_name='policy_rules')
    op.drop_index(op.f('ix_policy_rules_cpt_code'), table_name='policy_rules')
    op.drop_table('policy_rules')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cognito_sub'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cpt_codes_unbundling_group'), table_name='cpt_codes')
    op.drop_index(op.f('ix_cpt_codes_code'), table_name='cpt_codes')
    op.drop_table('cpt_codes')
    # ### end Alembic commands ###
